version = 1

test_patterns = ["**test**/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "jest",
    "mongo"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"