import type { Metadata } from "next";
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import { ConditionalLayout } from "@/components/layout/ConditionalLayout";

import '@mantine/core/styles.css';
import "./globals.css";

export const metadata: Metadata = {
  title: "Atlas AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider>
          <Notifications />
            <ConditionalLayout>
              {children}
            </ConditionalLayout>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
